### ISSUE TITLE
Add gallery e2e tests for the echo app

### ISSUE THREAD

**Issue by manskx** [Lightning-Universe/Echo#109]

**Comment by alecmerdler** [comment]
@manskx Could you add a description for this issue? We already have some [end-to-end tests using Cypress](https://github.com/Lightning-AI/LAI-Echo-App/blob/main/echo/ui/cypress/e2e/youtube-echo.spec.ts), but they aren't running in CI at the moment. Try running the e2e tests locally using `yarn run e2e:open`!
