### ISSUE TITLE
Copyright / unlawful use of downloading Youtube videos?

### ISSUE THREAD

**Issue by VirajVaitha123** [Lightning-Universe/Echo#138]
Hi there,

I was curious into how you bypassed YouTube's conditions on not downloading content from their website.

Even on YouTube you need to be a paying customer to even download videos in the first place.

I just wanted to address this and see your thoughts?

Thanks,

Viraj

**Comment by VirajVaitha123** [comment]
Any update on this, or just rolling with the copyright risk I guess?

**Comment by alecmerdler** [comment]
@VirajVaitha123 Thanks for bringing this to our attention, we've removed the YouTube transcription feature from https://lightning.ai/echo.
